[package]
name = "screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"


[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
] }
